Preprocessing data

In [3]:
import numpy as np
from sklearn import preprocessing #modul preprocessing

sample_data = np.array([[3.5, -10.2, 4.5], #data akan di generate menjadi numpy array
                      [5.5, 4.2, 3.3],
                      [0.6, 0.3, 3.0]])
sample_data

array([[  3.5, -10.2,   4.5],
       [  5.5,   4.2,   3.3],
       [  0.6,   0.3,   3. ]])

row = instance
col = fitures

In [4]:
sample_data.shape

(3, 3)

# binarisation

In [6]:
sample_data

array([[  3.5, -10.2,   4.5],
       [  5.5,   4.2,   3.3],
       [  0.6,   0.3,   3. ]])

In [24]:
preprocessor = preprocessing.Binarizer(threshold=0.5)
binarised = preprocessor.transform(sample_data)
binarised

array([[1., 0., 1.],
       [1., 1., 1.],
       [1., 0., 1.]])

nilai yang <= thresold maka = 0 

In [10]:
sample_data

array([[  3.5, -10.2,   4.5],
       [  5.5,   4.2,   3.3],
       [  0.6,   0.3,   3. ]])

In [28]:
preprocesor = preprocessing.MinMaxScaler(feature_range=(0, 1))
preprocesor.fit(sample_data)
Scaled_data = preprocesor.transform(sample_data)
Scaled_data

array([[0.59183673, 0.        , 1.        ],
       [1.        , 1.        , 0.2       ],
       [0.        , 0.72916667, 0.        ]])

dari data rentang nilai kecil = -10.2 ->5.5 dan di konversi rentang antara 0 sampai 1 dengan  cara MinMaxScaler. 

# Normalisation l1

In [31]:
sample_data

array([[  3.5, -10.2,   4.5],
       [  5.5,   4.2,   3.3],
       [  0.6,   0.3,   3. ]])

In [35]:
l1_normalised_data = preprocessing.normalize(sample_data, norm = 'l1')
l1_normalised_data

array([[ 0.19230769, -0.56043956,  0.24725275],
       [ 0.42307692,  0.32307692,  0.25384615],
       [ 0.15384615,  0.07692308,  0.76923077]])

parameter norm ='l1' berasosiasi = list absolut deviation.

# Normalisation l2

In [38]:
sample_data

array([[  3.5, -10.2,   4.5],
       [  5.5,   4.2,   3.3],
       [  0.6,   0.3,   3. ]])

l2_normalised_data = preprocessing.normalize(sample_data, norm = 'l2')
l2_normalised_data

ini adalah hasil normalisation l2 atau least Squares